#
# Copyright (C) 2020 Mod By-Ameng Openwrt
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-theme-Night
LUCI_PKGARCH:=all
PKG_VERSION:=1.5
PKG_RELEASE:=20200114


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
