#
# Copyright (C) 2019 Mod By-Ameng Openwrt
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-theme-Night
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=1


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
